### ISSUE TITLE
3.11 não abrindo // Comando -a  não executando

### ISSUE THREAD

**Issue by SCHROH** [ewertonhm/cmdSA#3]
Atualizando para a versão 3.11 não está executando o comando status, efetuado a configuração correta na variável Path

![image](https://user-images.githubusercontent.com/71782440/166809914-e82eb7cc-2671-4ea4-a473-2d66e94b2cd1.png)

Efetuado downgrade para versão 3.1 ou 2.12.2  que estava usando antes  e a função -a  está executando =/
![image](https://user-images.githubusercontent.com/71782440/166811810-59dfb7a5-9963-4d9e-a8c9-197a1f776479.png)

**Comment by ewertonhm** [comment]
Identifiquei um problema no comando -a nessa última versão, irei corrigir assim que possível.

porém o erro apresentado no seu print não parece ter relação,
no erro que vc enviou está dando um erro de conexão com o banco de dados, tente executar o script estando conectado na VPN

**Comment by SCHROH** [comment]
Entendi, então, estou executando o script da rede interna da filial, a VPN tá discando na RB interna no momento mas o erro persiste

Peguei uma versão mais antiga com o Daniel Bracker (que não sei dizer qual é) e funcionou kkkkk... 

![image](https://user-images.githubusercontent.com/71782440/166824953-bd48aa44-eb1c-4903-85d0-4351765b3118.png)


Mas na outra ainda o mesmo erro 😅

**Comment by ewertonhm** [comment]
Blz, irei verificar, por hora use a versão 3.0.x, o problema deve afetar só
a versão 3.1 em diante

Em qua., 4 de mai. de 2022 18:00, SCHROH ***@***.***>
escreveu:

**Comment by ewertonhm** [comment]
Resolvido no [Release 3.12](https://github.com/ewertonhm/cmdSA/releases/tag/3.12)
